spring:
  datasource:
    url: jdbc:mysql://localhost:33006/grabber?useUnicode=true&characterEncoding=UTF-8&useSSL=true&useAffectedRows=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      idle-timeout: 86000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      location: /home/frame/grabber/upload
recognition:
  fps: 5