spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:8080/grabber?useUnicode=true&characterEncoding=UTF-8&useSSL=true&useAffectedRows=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      idle-timeout: 86000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
recognition:
  fps: 5